env:
  browser: true
  node: true
  es2021: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - eslint:recommended
  - airbnb-base

rules: {
  no-console: off, 
  import/extensions: off
}
